### ISSUE TITLE
ERROR: py.test

### ISSUE THREAD

**Issue by jobtimus** [krischer/LASIF#1]
There is an error when I run py.test after the installation.

===================================
(lassie)Jobtimus-MacBook-Pro:doc Jobtimus$ py.test
Traceback (most recent call last):
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/Users/Jobtimus/Downloads/LASIF/conftest.py", line 19, in <module>
    import matplotlib
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/Jobtimus/anaconda/envs/lasif/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
ERROR: could not load /Users/Jobtimus/Downloads/LASIF/conftest.py

%%%%%%%%%%%%%%%%%%%%%%%%%%%%

There might be some problem during my installation.
Could you please suggest me how to solve  it?
Thank you so much.

**Comment by krischer** [comment]
This is a problem with your Python installation, not LASIF. See here for a fix:

http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8

Please reopen if that does not solve the issue.
